---
local:
  children:
    macbooks:
      hosts:
        127.0.0.1:
      vars: #macbook vars
        connection: local
    # macminis:
    #   hosts:
    #     xx.xx.xx.xx
  vars:
    local_user: &local_user emmanuel
    ansible_user: *local_user
    ansible_ssh_user: *local_user
    ansible_become_user: *local_user
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
