################################################################################
# Install
################################################################################
- name: Check homebrew path
  ansible.builtin.shell:
    cmd: which brew
  register: check_brew

- name: Install homebrew
  ansible.builtin.shell:
    cmd: $(which bash) -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  become: false
  when: '"/usr/local/bin/brew" not in check_brew.stdout'

################################################################################
# Taps
################################################################################
- name: Update homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: Tap a Homebrew repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ homebrew_taps }}"

################################################################################
# Formulae
################################################################################
- name: Upgrade all Formulae
  community.general.homebrew:
    upgrade_all: yes

- name: Install Formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ homebrew_installed_packages }}"

################################################################################
# Casks
################################################################################
- name: Upgrade all Casks
  community.general.homebrew_cask:
    upgrade_all: true

- name: Install Casks with install options
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: 'debug,appdir={{ homebrew_cask_appdir }}'
  with_items:
  - "{{ homebrew_cask_apps }}"
